apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
  namespace: default
  labels:
    app: nestjs-app
spec:
  type: NodePort
  selector:
    app: nestjs-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  sessionAffinity: None
