name: Destroy AWS Infrastructure

on:
  workflow_dispatch: # Manual trigger

env:
  TERRAFORM_VERSION: 1.5.7 # Update to version when needed
  AWS_REGION: eu-west-1

jobs:
  destroy-ecs-service:
    name: Destroy ECS service-related resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get ECS cluster name from remote state
        id: get_ecs_cluster_name
        run: |
          terraform init -backend-config="../../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
          echo "ECS_CLUSTER_NAME=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_ENV
        working-directory: infra/deployment/prod/ecs_cluster
        env:
          TF_IN_AUTOMATION: true

      - name: Get ECS service name from remote state
        id: get_ecs_service_name
        run: |
          terraform init -backend-config="../../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
          echo "ECS_SERVICE_NAME=$(terraform output -raw ecs_service_name)" >> $GITHUB_ENV
        working-directory: infra/deployment/prod/ecs_service
        env:
          TF_IN_AUTOMATION: true

      - name: Scale down ECS service
        run: aws ecs update-service --cluster ${{ env.ECS_CLUSTER_NAME }} --service ${{ env.ECS_SERVICE_NAME }} --desired-count 0 --force-new-deployment --region ${{ env.AWS_REGION }}

      - name: Wait for the ECS service to become stable
        run: aws ecs wait services-stable --cluster ${{ env.ECS_CLUSTER_NAME }} --services ${{ env.ECS_SERVICE_NAME }} --region ${{ env.AWS_REGION }}

      - name: Destroy Resources on the routing directory
        run: terraform destroy -var-file="../../terraform.tfvars" -var="ecr_app_image=some_non_relevant_value" -auto-approve
        working-directory: infra/deployment/prod/ecs_service

  destroy-routing:
    name: Destroy routing-related resources
    needs: destroy-ecs-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform on the routing directory
        run: terraform init -backend-config="../../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: infra/deployment/prod/routing

      - name: Destroy Resources on the routing directory
        run: terraform destroy -var-file="../../terraform.tfvars" -auto-approve
        working-directory: infra/deployment/prod/routing

  destroy-alb:
    name: Destroy ALB-related resources
    needs: destroy-ecs-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform on the ALB directory
        run: terraform init -backend-config="../../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: infra/deployment/prod/alb

      - name: Destroy Resources on the ALB directory
        run: terraform destroy -var-file="../../terraform.tfvars" -auto-approve
        working-directory: infra/deployment/prod/alb

  destroy-ecs-cluster:
    name: Destroy ECS cluster-related resources
    needs: [destroy-ecs-service, destroy-alb]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform on the ECS directory
        run: terraform init -backend-config="../../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: infra/deployment/prod/ecs_cluster

      - name: Destroy Resources on the ECS directory
        run: terraform destroy -var-file="../../terraform.tfvars" -auto-approve
        working-directory: infra/deployment/prod/ecs_cluster

  destroy-ssl:
    name: Destroy SSL certificate-related resources
    needs: destroy-alb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform on the SSL directory
        run: terraform init -backend-config="../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: infra/deployment/ssl

      - name: Destroy Resources on the SSL directory
        run: terraform destroy -var-file="../terraform.tfvars" -auto-approve
        working-directory: infra/deployment/ssl

  destroy-ecr:
    name: Destroy ECR-related resources
    runs-on: ubuntu-latest
    needs: [destroy-ecs-service, destroy-alb]
    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get ECR repository name from remote state
        id: get_ecr_repository_name
        run: |
          terraform init -backend-config="../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
          echo "ECR_REPOSITORY_NAME=$(terraform output -raw ecr_repository_name)" >> $GITHUB_ENV
        working-directory: infra/deployment/ecr
        env:
          TF_IN_AUTOMATION: true

      - name: Delete existing app images
        run: aws ecr batch-delete-image
          --repository-name ${{ env.ECR_REPOSITORY_NAME }}
          --image-ids "$(aws ecr list-images --repository-name ${{ env.ECR_REPOSITORY_NAME }} --query 'imageIds[*]' --output json --region ${{ env.AWS_REGION }})"
          --region ${{ env.AWS_REGION }}

      - name: Destroy resources on the ECR directory
        run: terraform destroy -var-file="../terraform.tfvars" -auto-approve
        working-directory: infra/deployment/ecr

  destroy-vpc:
    name: Destroy VPC-related resources
    needs: [destroy-ecs-cluster, destroy-alb, destroy-ssl, destroy-ecr]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform on the VPC directory
        run: terraform init -backend-config="../../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: infra/deployment/prod/vpc

      - name: Destroy Resources on the VPC directory
        run: terraform destroy -var-file="../../terraform.tfvars" -auto-approve
        working-directory: infra/deployment/prod/vpc
