name: Deploy AWS Route53 Hosted Zone and Terraform State Bucket (EKS)

on:
  workflow_dispatch: # Manual trigger only

env:
  TERRAFORM_VERSION: 1.10.3
  AWS_REGION: eu-west-1

jobs:
  deploy-terraform-state-bucket:
    name: Deploy Terraform State Bucket (EKS)
    uses: ./.github/workflows/eks_deploy_terraform_state_bucket.yaml # Note: Copy to .github/workflows first
    with:
      github_head_commit_message: "Manual trigger for EKS infrastructure"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-hosted-zone:
    name: Deploy Route53 Hosted Zone (EKS)
    needs: deploy-terraform-state-bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init -backend-config="../backend-config.hcl" -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: infra-eks/deployment/hosted_zone

      - name: Validate IaC changes
        run: terraform plan -var-file="../common.tfvars" -var-file="../domain.tfvars"
        working-directory: infra-eks/deployment/hosted_zone

      - name: Create AWS Route53 Hosted Zone
        run: terraform apply -var-file="../common.tfvars" -var-file="../domain.tfvars" -auto-approve
        working-directory: infra-eks/deployment/hosted_zone
